[package]
name = "simple-editor"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.18"
wasm-bindgen = "0.2"
novel-archives-text = { git = "https://github.com/novel-archives/novel-archives-text" }
derive-new = "0.5.9"
